[package]
name = "slash-wiki-rest-rust"
version = "0.1.0"
authors = ["Luna <75589876+they-them@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.6"
rocket_contrib = "0.4.6"
serde = { version = "1.0.115", features = ["derive"] }
urlencoding = "1.1.1"